/* src/config_coinmp.h.  Generated by configure.  */
/* src/config_cbc.h.in. */

/* Version number of project */
#define COINMP_VERSION "1.7"

/* Major Version number of project */
#define COINMP_VERSION_MAJOR 1

/* Minor Version number of project */
#define COINMP_VERSION_MINOR 7

/* Release Version number of project */
#define COINMP_VERSION_RELEASE 9999
