/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* SVN revision number of project */
#define COINMP_SVN_REV 640

/* Version number of project */
#define COINMP_VERSION "1.7"

/* Major Version number of project */
#define COINMP_VERSION_MAJOR 1

/* Minor Version number of project */
#define COINMP_VERSION_MINOR 7

/* Release Version number of project */
#define COINMP_VERSION_RELEASE 9999

/* Define to the debug sanity check level (0 is no test) */
#define COIN_COINMP_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_COINMP_VERBOSITY 0

/* Define to 1 if the Cbc package is available */
#define COIN_HAS_CBC 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "coinmp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coinmp@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "CoinMP"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "CoinMP 1.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "coinmp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.7"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.7"
